repos:
  - repo: https://github.com/lsst-ts/pre-commit-xmllint
    rev: v1.0.0
    hooks:
      - id: format-xmllint
        entry: extract_xml_from_pptx.sh
        language: script
        files: .(pptx|xml|rels)$